version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  # REST API 포트
      - "6334:6334"  # gRPC 포트
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"  # 로그 레벨 (DEBUG, INFO, WARN, ERROR)
      QDRANT__STORAGE__PATH: "/qdrant/storage"
      QDRANT__TELEMETRY_DISABLED: "false"  # Qdrant 원격 Telemetry 비활성화 옵션
      QDRANT__SERVICE__GRPC_PORT: "6334"  # gRPC 서비스 포트 설정
      QDRANT__SERVICE__HTTP_PORT: "6333"  # REST API 포트 설정
      QDRANT__CLUSTER__ENABLED: "false"  # 클러스터링 옵션 (true로 설정 시 클러스터 모드 활성화)
      QDRANT__SEARCH__DEFAULT_HNSW_EF: "64"  # HNSW 검색 성능 최적화 파라미터
      QDRANT__SEARCH__DEFAULT_FULL_SCAN_THRESHOLD: "10000"  # 전체 검색 허용 임계값
      QDRANT__STORAGE__SNAPSHOT_INTERVAL_SEC: "86400"  # 자동 스냅샷 저장 간격 (하루 단위)

    deploy:
      resources:
        limits:
          cpus: "2.0"  # 최대 2개 CPU 코어 사용
          memory: "4G"  # 최대 4GB RAM 사용
        reservations:
          cpus: "1.0"  # 최소 1개 CPU 코어 확보
          memory: "2G"  # 최소 2GB RAM 확보

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s  # 30초마다 헬스체크 실행
      timeout: 5s
      retries: 3

volumes:
  qdrant_data:
    driver: local
